In [41]:
data = [{'Fire Alarm': 0.0, 'NC0.5': -0.9740387138719555, 'NC1.0': -1.065365192950446, 'PM1.0': -0.9954259790010621, 'PM2.5': -1.0574310874177248, 'Temperature[C]': 0.9518198046677115, 'utc': 1654733415.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.9753169220579497, 'NC1.0': -1.0706158244069928, 'PM1.0': -0.9954259790010621, 'PM2.5': -1.0574310874177248, 'Temperature[C]': 0.9538159000254193, 'utc': 1654733416.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.9753169220579497, 'NC1.0': -1.0749913506207815, 'PM1.0': -1.0043854307052926, 'PM2.5': -1.0664159985033135, 'Temperature[C]': 0.9559655411798734, 'utc': 1654733417.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.9753169220579497, 'NC1.0': -1.0828672978056013, 'PM1.0': -1.0043854307052926, 'PM2.5': -1.0754009095889023, 'Temperature[C]': 0.9579616365375807, 'utc': 1654733418.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.9753169220579497, 'NC1.0': -1.0863677187766325, 'PM1.0': -1.0043854307052926, 'PM2.5': -1.0754009095889023, 'Temperature[C]': 0.9599577318952885, 'utc': 1654733419.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.9753169220579497, 'NC1.0': -1.0933685607186947, 'PM1.0': -1.0043854307052926, 'PM2.5': -1.084385820674491, 'Temperature[C]': 0.9619538272529958, 'utc': 1654733420.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.9753169220579497, 'NC1.0': -1.095993876446968, 'PM1.0': -1.0043854307052926, 'PM2.5': -1.084385820674491, 'Temperature[C]': 0.9641034684074505, 'utc': 1654733421.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.9753169220579497, 'NC1.0': -1.1012445079035147, 'PM1.0': -1.0043854307052926, 'PM2.5': -1.084385820674491, 'Temperature[C]': 0.9660995637651577, 'utc': 1654733422.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.9753169220579497, 'NC1.0': -1.10299471838903, 'PM1.0': -1.0043854307052926, 'PM2.5': -1.0933707317600796, 'Temperature[C]': 0.9680956591228655, 'utc': 1654733423.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.9753169220579497, 'NC1.0': -1.1064951393600613, 'PM1.0': -1.0043854307052926, 'PM2.5': -1.0933707317600796, 'Temperature[C]': 0.9700917544805728, 'utc': 1654733424.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.9753169220579497, 'NC1.0': -1.1082453498455767, 'PM1.0': -1.0133448824095233, 'PM2.5': -1.0933707317600796, 'Temperature[C]': 0.9720878498382807, 'utc': 1654733425.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.9254668028041744, 'NC1.0': -0.4370396286503701, 'PM1.0': -0.8162369449164513, 'PM2.5': -0.4913816890256408, 'Temperature[C]': 0.9742374909927348, 'utc': 1654733426.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.929301427362157, 'NC1.0': -0.4982969956434138, 'PM1.0': -0.8341558483249124, 'PM2.5': -0.5452911555391725, 'Temperature[C]': 0.976233586350442, 'utc': 1654733427.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.9395270928501109, 'NC1.0': -0.635688518756383, 'PM1.0': -0.8699936551418345, 'PM2.5': -0.6710799107374135, 'Temperature[C]': 0.9782296817081498, 'utc': 1654733428.0}, {'Fire Alarm': 0.0, 'NC0.5': -0.9433617174080937, 'NC1.0': -0.6881948333218489, 'PM1.0': -0.8879125585502956, 'PM2.5': -0.7160044661653567, 'Temperature[C]': 0.9802257770658571, 'utc': 1654733429.0}, {'Fire Alarm': 1.0, 'NC0.5': 1.2347050315260912, 'NC1.0': 1.2326611745314475, 'PM1.0': 1.2354774953523426, 'PM2.5': 1.2337212394073778, 'Temperature[C]': -1.022625595698542, 'utc': 1654736594.0}, {'Fire Alarm': 1.0, 'NC0.5': 1.1720728304123735, 'NC1.0': 1.1661531760818573, 'PM1.0': 1.172761333422729, 'PM2.5': 1.1708268618082576, 'Temperature[C]': -1.0244681452595028, 'utc': 1654736595.0}, {'Fire Alarm': 1.0, 'NC0.5': 1.1413958339485115, 'NC1.0': 1.132899176857062, 'PM1.0': 1.1458829783100375, 'PM2.5': 1.1348872174659028, 'Temperature[C]': -1.0264642406172102, 'utc': 1654736596.0}, {'Fire Alarm': 1.0, 'NC0.5': 1.0608687182308745, 'NC1.0': 1.047138863066801, 'PM1.0': 1.0562884612677321, 'PM2.5': 1.0450381066100165, 'Temperature[C]': -1.0283067901781708, 'utc': 1654736597.0}, {'Fire Alarm': 1.0, 'NC0.5': 1.0276353053950245, 'NC1.0': 1.0112595481137328, 'PM1.0': 1.0294101061550402, 'PM2.5': 1.0180833733532506, 'Temperature[C]': -1.0303028855358785, 'utc': 1654736598.0}, {'Fire Alarm': 1.0, 'NC0.5': 1.0059057662331223, 'NC1.0': 0.9893819170447886, 'PM1.0': 1.0025317510423488, 'PM2.5': 0.9911286400964846, 'Temperature[C]': -1.0321454350968393, 'utc': 1654736599.0}, {'Fire Alarm': 1.0, 'NC0.5': 0.9892890598151971, 'NC1.0': 0.9701296017041176, 'PM1.0': 0.9846128476338877, 'PM2.5': 0.9731588179253072, 'Temperature[C]': -1.0341415304545467, 'utc': 1654736600.0}, {'Fire Alarm': 1.0, 'NC0.5': 0.95094281423537, 'NC1.0': 0.9298747605372605, 'PM1.0': 0.9487750408169655, 'PM2.5': 0.9372191735829527, 'Temperature[C]': -1.0359840800155078, 'utc': 1654736601.0}, {'Fire Alarm': 1.0, 'NC0.5': 0.95094281423537, 'NC1.0': 0.9298747605372605, 'PM1.0': 0.9487750408169655, 'PM2.5': 0.9372191735829527, 'Temperature[C]': -1.0379801753732152, 'utc': 1654736602.0}, {'Fire Alarm': 1.0, 'NC0.5': 0.9573338551653411, 'NC1.0': 0.9368756024793226, 'PM1.0': 0.9577344925211962, 'PM2.5': 0.9372191735829527, 'Temperature[C]': -1.039822724934176, 'utc': 1654736603.0}, {'Fire Alarm': 1.0, 'NC0.5': 0.9816198106992318, 'NC1.0': 0.9622536545192978, 'PM1.0': 0.9756533959296573, 'PM2.5': 0.9641739068397188, 'Temperature[C]': -1.0418188202918837, 'utc': 1654736604.0}, {'Fire Alarm': 1.0, 'NC0.5': 0.9956801007451683, 'NC1.0': 0.9780055488889373, 'PM1.0': 0.9935722993381184, 'PM2.5': 0.9821437290108961, 'Temperature[C]': -1.0436613698528445, 'utc': 1654736605.0}, {'Fire Alarm': 1.0, 'NC0.5': 1.0033493498611339, 'NC1.0': 0.9858814960737575, 'PM1.0': 1.0025317510423488, 'PM2.5': 0.9911286400964846, 'Temperature[C]': -1.045657465210552, 'utc': 1654736606.0}, {'Fire Alarm': 1.0, 'NC0.5': 0.9931236843731799, 'NC1.0': 0.9753802331606644, 'PM1.0': 0.9935722993381184, 'PM2.5': 0.9731588179253072, 'Temperature[C]': -1.0475000147715126, 'utc': 1654736607.0}]

In [42]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Convert to DataFrame
df = pd.DataFrame(data)

# Separate features and target
X = df.drop(columns=['Fire Alarm', 'utc'])
y = df['Fire Alarm']



In [43]:
import numpy as np
from sklearn.model_selection import StratifiedKFold

KFModel = StratifiedKFold(n_splits=5)
p_rf= np.zeros(y.shape[0])

In [44]:
p_rf

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix


for n in range(10,100,10):
    for train,test in KFModel.split(X,y):
        X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=33)
        clf = GradientBoostingClassifier(n_estimators=100,learning_rate=1.0,max_depth=1,random_state=33)
        clf.fit(X_train,Y_train)
        Y_pred = clf.predict(X_test)
        cm=confusion_matrix(Y_test,Y_pred)
        print(cm)
    print('Score for n:',n,":",accuracy_score(Y_test,Y_pred))

[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
Score for n: 10 : 1.0
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
Score for n: 20 : 1.0
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
Score for n: 30 : 1.0
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
Score for n: 40 : 1.0
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
Score for n: 50 : 1.0
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
Score for n: 60 : 1.0
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
Score for n: 70 : 1.0
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
Score for n: 80 : 1.0
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
[[4 0]
 [0 2]]
Score for n: 90 : 1.0


In [47]:
# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [48]:
X_train

NC0.5     NC1.0     PM1.0     PM2.5  Temperature[C]
21  0.989289  0.970130  0.984613  0.973159       -1.034142
0  -0.974039 -1.065365 -0.995426 -1.057431        0.951820
26  0.995680  0.978006  0.993572  0.982144       -1.043661
13 -0.939527 -0.635689 -0.869994 -0.671080        0.978230
15  1.234705  1.232661  1.235477  1.233721       -1.022626
11 -0.925467 -0.437040 -0.816237 -0.491382        0.974237
17  1.141396  1.132899  1.145883  1.134887       -1.026464
1  -0.975317 -1.070616 -0.995426 -1.057431        0.953816
4  -0.975317 -1.086368 -1.004385 -1.075401        0.959958
5  -0.975317 -1.093369 -1.004385 -1.084386        0.961954
2  -0.975317 -1.074991 -1.004385 -1.066416        0.955966
24  0.957334  0.936876  0.957734  0.937219       -1.039823
3  -0.975317 -1.082867 -1.004385 -1.075401        0.957962
23  0.950943  0.929875  0.948775  0.937219       -1.037980
25  0.981620  0.962254  0.975653  0.964174       -1.041819
18  1.060869  1.047139  1.056288  1.045038       -1.028307
28  0.993124  0.975380  0.993572  0.973159       -1.047500
20  1.005906  0.989382  1.002532  0.991129       -1.032145
7  -0.975317 -1.101245 -1.004385 -1.084386        0.966100
10 -0.975317 -1.108245 -1.013345 -1.093371        0.972088
14 -0.943362 -0.688195 -0.887913 -0.716004        0.980226
19  1.027635  1.011260  1.029410  1.018083       -1.030303
6  -0.975317 -1.095994 -1.004385 -1.084386        0.964103

In [51]:
# Define parameter grid for GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC


param_grid = {
    'RandomForestClassifier': {
        'n_estimators': [10, 50, 100],
        'max_depth': [None, 10, 20, 30]
    },
    'SVC': {
        'C': [0.1, 1, 10],
        'kernel': ['linear', 'rbf']
    }
}

# Create classifiers
classifiers = {
    'RandomForestClassifier': RandomForestClassifier(),
    'SVC': SVC()
}

best_estimators = {}
best_scores = {}

# GridSearch for each classifier
for clf_name, clf in classifiers.items():
    print(f"Running GridSearchCV for {clf_name}")
    grid_search = GridSearchCV(clf, param_grid[clf_name], cv=5, scoring='accuracy')
    grid_search.fit(X_train, y_train)
    best_estimators[clf_name] = grid_search.best_estimator_
    best_scores[clf_name] = grid_search.best_score_

# Print best scores and parameters for each classifier
for clf_name in best_estimators:
    print(f"Best estimator for {clf_name}: {best_estimators[clf_name]}")
    print(f"Best score for {clf_name}: {best_scores[clf_name]}")


Running GridSearchCV for RandomForestClassifier
Running GridSearchCV for SVC
Best estimator for RandomForestClassifier: RandomForestClassifier(max_depth=20)
Best score for RandomForestClassifier: 0.67
Best estimator for SVC: SVC(C=0.1)
Best score for SVC: 0.48
